disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Limerio"

[params]
displayName = "🏴󠁧󠁢󠁥󠁮󠁧󠁿 English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "Limerio"
email = "contact@limerio.com"
image = "https://avatars.githubusercontent.com/u/44976231?v=4"
imageQuality = 96
headline = "Full stack developer"
bio = "Full stack developer"
links = [
  { email = "mailto:contact@limerio.dev" },
  { github = "https://github.com/Limerio" },
]
